config/routes.rb
Rails.application.routes.draw do
  resources :locations, except: [:update, :edit, :destroy]
  root 'locations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :full_address
  after_validation :geocode, :if => :address_changed?

  def full_address
   [address, city, postcode].compact.join(',')
  end

  VALID_POSTCODE_REGEX = /\A\s*((GIR\s*0AA)|((([A-PR-UWYZ][0-9]{1,2})|(([A-PR-UWYZ][A-HK-Y][0-9]{1,2})|(([A-PR-UWYZ][0-9][A-HJKSTUW])|([A-PR-UWYZ][A-HK-Y][0-9][ABEHMNPRVWXY]))))\s*[0-9][ABD-HJLNP-UW-Z]{2}))\s*\Z/i

  validates :postcode, presence: true, format: { with: VALID_POSTCODE_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], params[:distance] || 300, :order => 'distance')
    else
      @locations = Location.all.order("created_at DESC")
    end
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      flash[:success] = "Place added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def location_params
    params.require(:location).permit(:company_name, :address, :city,
                                    :postcode, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindSubcontractor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/f40685afe6.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:700" rel="stylesheet">
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>

    <%= f.label :company_name %>
    <%= f.text_field :company_name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :postcode %>
    <%= f.text_field :postcode %>


  <%= f.submit 'Add!' %>
<% end %>

app/views/locations/index.html.erb
<div class="container">
  <div class="starter-template">
    <i class="fa fa-building fa-2x"></i> <h3>SubContractor Finder.</h3>
      <p class="lead">Use this postcode search to quickly find subcontractors in your area</p>
      
      <p><%= form_tag locations_path, :method => :get do %>
        <%= label :search, "Postcode : " %>
        <%= text_field_tag :search, params[:search], placeholder: "e.g M20 2WZ" %>

        <%= label :distance, "Distance(km) : " %>
        <%= text_field_tag :distance, params[:distance], placeholder: "e.g 35" %>

        <%= submit_tag "Subcontractors near", :name => nil, class: "btn-sm btn-success" %>
      </p>

    <% end %>


    <% if @locations.blank? %>
      <div class="alert alert-danger message-font text-center" role="alert">
      <h3>No Subcontractors found within this area.</h3>
    </div>
      <% else %>

     <table class="table">
        <tr>
          <td><strong>Company Name</strong></td>
          <td><strong>Address</strong></td>
          <td><strong>City</strong></td>
          <td><strong>Postcode</strong></td>
        </tr>

        <% @locations.each do |location| %>
        <tr>
          <td><%= location.company_name %></td>
          <td><%= location.address %></td>
          <td><%= location.city %></td>
          <td><%= location.postcode %></td>
        </tr>
        <% end %>
      </table>
    <% end %>
 </div>

  <footer class="footer">
      <div class="container">
        <p>SubContractor App 2017</p>
      </div>
    </footer>
</div>

app/views/locations/new.html.erb
<div class="container">
<h1>Add Location</h1>

<%= render 'form' %>
</div>